const CHANGE_CATEGORY = "CHANGE_CATEGORY";
const CHANGE_COUNT = "CHANGE_COUNT";
const NEXT_QUESTION = "NEXT_QUESTION";
const RESET_TEST = "RESET_TEST";

export { CHANGE_CATEGORY, CHANGE_COUNT, NEXT_QUESTION, RESET_TEST };
