const CHANGE_CATEGORY = "CHANGE_CATEGORY";
const CHANGE_COUNT = "CHANGE_COUNT";
const NEXT_QUESTION = "NEXT_QUESTION";
const CHANGE_COMPLETED_STATUS = "CHANGE_COMPLETED_STATUS";

export {
  CHANGE_CATEGORY,
  CHANGE_COUNT,
  NEXT_QUESTION,
  CHANGE_COMPLETED_STATUS,
};
